# Server
server.port=8080
spring.datasource.url=jdbc:postgresql://ep-divine-morning-aca33ldg-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_tbzT9NfA2qHC&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect