# Server
server.port=8080
spring.datasource.url=jdbc:postgresql://ep-divine-morning-aca33ldg-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_tbzT9NfA2qHC&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.show-extensions=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.use-root-path=true